### ISSUE TITLE
Logging work for an issue logs the time for a wrong issue

### ISSUE THREAD

**Issue by feldifux** [web-pal/chronos-timetracker#95] opened 2018-03-21 09:34 UTC
## Expected Behavior
I log time for an issue, the issue is then changed and the time is added for another issue. Does not happen when I restart the Chronos app, but after I log time for one issue and then want to log for another, the first one is used.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Chronos-timetracker version:
  - OS:

**Comment by VladimirPal** [comment] 2018-03-21 10:29
@feldifux 
What OS do you use? This issues from one project? I can't reproduce it.

**Comment by Kondamon** [comment] 2018-03-21 10:48
@VladimirPal I can reproduce this:

1. Select Board
2. Select Sprint
3. Search for anything in the search field e.g. "abc"
4. Select any issue within the issue field
5. Press the Log Work button of the issue and save any time e.g. 2h with Log Work
6. The time is added to another issue 

Chronos-timetracker version: 2.6.2
OS: macOS HighSierra 10.13.2

**Comment by VladimirPal** [comment] 2018-03-21 11:00
@Kondamon Thanks, will fixed today

**Comment by Architektor** [comment] 2018-03-21 16:00
fixed in 2.6.3

**Closed** 2018-03-21 16:00 UTC
Labels: In progress :hammer:, bug :beetle:

**Comment by VladimirPal** [comment] 2018-03-22 10:38
@feldifux @Kondamon Is it work guys?

**Comment by feldifux** [comment] 2018-03-22 10:41
Yes it is working again, thx.
You guys should really do some unit testing to make sure such regression bugs dont pop up. ;)

**Comment by VladimirPal** [comment] 2018-03-22 10:59
true
