### ISSUE TITLE
Issue on mac OS Mojave

### ISSUE THREAD

**Issue by AhmedBarghash** [web-pal/chronos-timetracker#143] opened 2018-11-20 09:05 UTC
## Expected Behavior

enter my team name.
enter my username and password
see the main screen.

## Actual Behavior

enter my team name.
enter my username and password
keep loading and no action.

## Steps to Reproduce the Problem

  1. the same action happens every single time. 

## Specifications

  - Chronos-timetracker version:
  - OS:

**Comment by VladimirPal** [comment] 2018-11-23 13:10
@AhmedBarghash  We were unable to reproduce the problem on mac OS Mojave.
Probably the reason is something else. Try to clear a cache and let us know please.
Chronos -> Clear cache.

**Comment by AhmedBarghash** [comment] 2018-11-27 01:42
@VladimirPal 
I tried to clear cache. same thing happend loading and no action 
<img width="499" alt="screen shot 2018-11-27 at 3 40 26 am" src="https://user-images.githubusercontent.com/18752334/49052872-6693a100-f1f6-11e8-8b7b-8f0ba8e5048e.png">

**Comment by kevingelion** [comment] 2018-11-29 17:02
Here to report the same issue - I just keep seeing a spinner. This is after upgrading and having my cache updated (I was previously logged in with the old version then logged out after updating).

I tried clearing my cache and everything. I am prompted for my email and then told I am being taken to my SSO provider but nothing happens & I just see the spinner. Same behavior after trying to log in with Google.

**Comment by schinckel** [comment] 2019-01-17 02:35
I'm seeing this too. Brand new user, Mojave.

**Comment by schinckel** [comment] 2019-01-17 02:48
I believe it's when it tries to render the 2FA page.

**Comment by VladimirPal** [comment] 2019-02-18 12:28
Hi!
Could you try please 3.0.0-beta, it should be fixed

**Comment by jhult** [comment] 2019-02-18 20:44
I am running version 3.0.0 on macOS 10.14.3 and have no problems logging in.

I do not currently use 2FA nor SSO.

**Comment by schinckel** [comment] 2019-02-19 23:49
Yes, able to log in using 2FA now.

**Closed** 2019-02-20 06:44 UTC
